application-settings:
  refresh-rate: 10
lifx-api:
  key: ""
status-colors:
  available-color: "purple" # see api docs for color names and options
  busy-color: "red"
  do-not-disturb-color: "red"
  away-color: "off" # to have light tun off
  be-right-back-color: "yellow"
  offline-color: "off" # to have light tun off
light-settings:
  label: "Status Light"
  brightness: 0.5
  color-change-speed: 3.0