application-settings:
  refresh-rate: 10 # in seconds
lifx-api:
  key: ""
status-colors:
  available-color: "green" # see api docs for color names and options
  busy-color: "red"
  do-not-disturb-color: "red"
  away-color: "off" # to have light tun off
  be-right-back-color: "yellow"
  offline-color: "off" # to have light tun off
light-settings:
  label: "Status Light"
  id: "d073d572fceb"
  brightness: 0.5 # from 0 to 1
  color-change-speed: 3.0 # in seconds